# Generated by Django 3.2.4 on 2021-06-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saloon.services', verbose_name='kasbi'),
        ),
    ]
