# Generated by Django 3.2.5 on 2021-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0006_auto_20210718_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('tel', models.CharField(blank=True, max_length=25, null=True)),
                ('view', models.BooleanField(default=False)),
            ],
        ),
    ]
