# Generated by Django 3.2.5 on 2021-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0008_alter_usedprod_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='residue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
